"""Initial migration

Revision ID: 2ebd5631d2a5
Revises: 
Create Date: 2025-05-19 14:02:37.784542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ebd5631d2a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('business_number', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('business_number')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='상품명'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='상품코드/SKU'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='분류'),
    sa.Column('brand', sa.String(length=100), nullable=True, comment='브랜드'),
    sa.Column('model', sa.String(length=100), nullable=True, comment='모델명'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='상세설명'),
    sa.Column('current_stock', sa.Integer(), nullable=False, comment='현재 재고 수량'),
    sa.Column('minimum_stock', sa.Integer(), nullable=False, comment='최소 재고 수량'),
    sa.Column('price', sa.Float(), nullable=False, comment='판매가격'),
    sa.Column('cost_price', sa.Float(), nullable=True, comment='원가'),
    sa.Column('tax_included', sa.Boolean(), nullable=True, comment='부가세 포함 여부'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='등록일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='수정일시'),
    sa.Column('company_id', sa.Integer(), nullable=False, comment='회사 ID'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'company_admin', 'user'), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('purchase_infos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False, comment='제품 ID'),
    sa.Column('supplier_name', sa.String(length=100), nullable=False, comment='공급업체명'),
    sa.Column('business_number', sa.String(length=20), nullable=True, comment='사업자등록번호'),
    sa.Column('supplier_contact', sa.String(length=100), nullable=True, comment='담당자'),
    sa.Column('supplier_address', sa.Text(), nullable=True, comment='주소'),
    sa.Column('supplier_phone', sa.String(length=20), nullable=True, comment='전화번호'),
    sa.Column('supplier_email', sa.String(length=100), nullable=True, comment='이메일'),
    sa.Column('invoice_number', sa.String(length=50), nullable=True, comment='송장번호'),
    sa.Column('purchase_date', sa.DateTime(), nullable=False, comment='구매일자'),
    sa.Column('expected_delivery_date', sa.DateTime(), nullable=True, comment='예상 납기일'),
    sa.Column('actual_delivery_date', sa.DateTime(), nullable=True, comment='실제 납기일'),
    sa.Column('quantity', sa.Integer(), nullable=False, comment='수량'),
    sa.Column('unit_price', sa.Float(), nullable=False, comment='단가'),
    sa.Column('tax_rate', sa.Float(), nullable=True, comment='세율(%)'),
    sa.Column('tax_amount', sa.Float(), nullable=True, comment='세액'),
    sa.Column('discount', sa.Float(), nullable=True, comment='할인금액'),
    sa.Column('total_price', sa.Float(), nullable=False, comment='총금액'),
    sa.Column('payment_terms', sa.String(length=50), nullable=True, comment='결제조건'),
    sa.Column('payment_due_date', sa.DateTime(), nullable=True, comment='결제기한'),
    sa.Column('payment_status', sa.String(length=20), nullable=False, comment='결제상태'),
    sa.Column('payment_method', sa.String(length=50), nullable=True, comment='결제방법'),
    sa.Column('paid_amount', sa.Float(), nullable=True, comment='결제금액'),
    sa.Column('paid_date', sa.DateTime(), nullable=True, comment='결제일자'),
    sa.Column('notes', sa.Text(), nullable=True, comment='비고'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='수정일시'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='생성자'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('sale_date', sa.DateTime(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=True),
    sa.Column('customer_contact', sa.String(length=100), nullable=True),
    sa.Column('customer_email', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'shipped', 'delivered', 'cancelled', 'returned', name='sale_status'), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale_records')
    op.drop_table('purchase_infos')
    op.drop_table('users')
    op.drop_table('products')
    op.drop_table('companies')
    # ### end Alembic commands ###
